### ISSUE TITLE
Semver releases

### ISSUE THREAD

**Issue by nolash** [teamsempo/SempoBlockchain#207]
SInce this is an open source project that is actively in use, I would recommend that release tags and semver versioning be implemented.

Specifically, I would request that the versioning scheme makes very clear when compatibility changes occur. That means minor version change in the `0.x` series, and major version change in `1.x` series and above.

**Comment by enjeyw** [comment]
We actually have semver already!
Backend here:
https://github.com/teamsempo/SempoBlockchain/blob/master/config.py#L7
Client here:
https://github.com/teamsempo/SempoBlockchain/blob/master/app/package.json#L3

You're right that they should also go onto the formal github release tags
though - given we have both frontend and backend, what's ur thought on how
to do it best?

**Comment by nolash** [comment]
Good question. Perhaps change in either should result in the higher version number for both plus one;

after a change in only client:

client 0.0.2
server 0.0.1

after a change in server and client:

client 0.0.3
server 0.0.3

?

**Comment by enjeyw** [comment]
Mmmmm I think it feels weird to increment a version of software when there's literally no change to the code base. We could be just overthinking it, and we tag both on the release `c-0.0.2 s-0.1.4`

**Comment by nolash** [comment]
That's fine. In either case one would probably be lagging behind the other, better then perhaps that they're disassociated. Not sure about adding the server version in the version string. Probably should be a separate file describing that?

**Comment by tristanhcole** [comment]
Closed by #631 and https://github.com/teamsempo/SempoBlockchain/releases
