### ISSUE TITLE
Pin reset not resetting pin_failed_attempts counter

### ISSUE THREAD

**Issue by WillRuddick** [teamsempo/SempoBlockchain#213]
https://github.com/GrassrootsEconomics/CIC-Docs/issues/64

After clicking on pin reset for a user, the counter for failed attempts is still at three.

We can't therefore know and call up people with blocked pins (often people don't have airtime to call us)

**Comment by tristanhcole** [comment]
I couldn't exactly reproduce this on master branch. When reset pin button is clicked, the count is being reset on the DB, _but the frontend isn't updating correctly_ (so still showing previous failed attempts), however, if you refresh the page it will show 0 attempts as pin has been correctly reset. 

Could you confirm this is what is happening and I'll put in a small PR to fix this?

**Comment by WillRuddick** [comment]
thanks @tristanhcole it was indeed just cosmetic - refreshing the page does show the correct number .
