### ISSUE TITLE
App-side retry functionality for transactions celery tasks are lost due to redis data loss

### ISSUE THREAD

**Issue by enjeyw** [teamsempo/SempoBlockchain#331]
**Is your feature request related to a problem? Please describe.**

Pulling in feature from https://github.com/teamsempo/SempoBlockchain/pull/262:

We've had locally-created credit transfers fail to convert into blockchain transactions in the past due to them never making it to the worker - for example if redis has a data-loss while the transaction is in a queue.
It's super rare (needs redis to be whiped), but we need a simple way of getting those transaction back into the queue. 

**Describe the solution you'd like**
Even just manually having an api call for re-submitting transactions to the queue would have huge utility, though it's critical that this function call is idempotent. 

**Describe alternatives you've considered**
None

**Additional context**

**Comment by tristanhcole** [comment]
@michielderoos is this resolved by #431 ?

**Comment by tristanhcole** [comment]
Closed #431
