### ISSUE TITLE
Dynamically accommodate paths in setup

### ISSUE THREAD

**Issue by EDsCODE** [teamsempo/SempoBlockchain#388]
**Describe the bug**
The paths in the readme are hardcoded so there are occasional places that don't "just work". 

Example below:

**To Reproduce**
1. Go to README
2. Call `./devtools/install_python_requirements.sh` from base directory

**Expected behavior**
The above will error because cd `../app` will be called but if you're in root directory this will take you to parent directory outside of the project. This happens at various places such as `./devtools/quick_setup_script.sh

**Additional context**

**Comment by michielderoos** [comment]
Fixed in moving utils to dedicated directory
