### ISSUE TITLE
Difficulty running Python app for the first time.

### ISSUE THREAD

**Issue by lucianstroie** [teamsempo/SempoBlockchain#43]
I get the following error when running `python ./run.py` for the first time:

```
ENV_DEPLOYMENT_NAME: local
with BUILD_HASH: null
ATTEMPT LOAD LOCAL CONFIG
Traceback (most recent call last):
  File "./app/run.py", line 11, in <module>
    from server import create_app
  File "/Users/lucian/Desktop/SempoBlockchain/app/server/__init__.py", line 15, in <module>
    import config
  File "/Users/lucian/Desktop/SempoBlockchain/config.py", line 76, in <module>
    raise Exception("Missing Common Config File")
Exception: Missing Common Config File
```

**Comment by lucianstroie** [comment]
Python 3.6.8
pip 19.3.1

**Comment by enjeyw** [comment]
Oh yep, current Sempo requires two sets of config files with tokens keys etc in it to get started -connecting to INFURA gateway and the like; I can send you a template, but there's a few services you'd need to sign up to. It's actually my next TODO to make it easier to launch for the first time.

**Comment by lucianstroie** [comment]
Yes, please send me the template.
If you would like I could just add this step to the README, if that helps.

**Comment by enjeyw** [comment]
Yeah that’d be great. I’m just about to take off on a flight (on mobile RN), but will send you something ASAP.

**Comment by enjeyw** [comment]
Closed for now as we've had some improvements on this one:
https://github.com/teamsempo/SempoBlockchain/pull/202
https://github.com/teamsempo/SempoBlockchain/pull/178

**Comment by enjeyw** [comment]
Closed for now as we've had some improvements on this one:
https://github.com/teamsempo/SempoBlockchain/pull/202
https://github.com/teamsempo/SempoBlockchain/pull/178
